FROM mcr.microsoft.com/devcontainers/base:bookworm

# Install necessary packages, wget is needed to download Microsoft packages for dotnet apt-sources
RUN \
    apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        python3 \
        python-is-python3 \
        pipx \
        wget \
        mosquitto \
    && apt-get clean
  
RUN \
    wget https://packages.microsoft.com/config/debian/12/packages-microsoft-prod.deb -O packages-microsoft-prod.deb \
    && dpkg -i packages-microsoft-prod.deb \
    && rm packages-microsoft-prod.deb

RUN \
    apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        dotnet-sdk-8.0 \
    && apt-get clean

RUN pipx install poetry

COPY mosquitto.conf /etc/mosquitto/mosquitto.conf
COPY start.sh /start.sh
RUN chmod +x /start.sh

RUN mkdir -p /var/run/mosquitto

ENTRYPOINT /start.sh
